### ISSUE TITLE
Unable to install PointUlility on OpenPlotter V.4

### ISSUE THREAD

**Issue by Erickalon** [antipole2/PointUtility#2]
On Raspberry 4 running Openplotter V.4 and OpenCPN 5.8.4, Javascript V.3  is installed but PointUtility fails to compile. 
After starting run I got the message "SyntaxError: source decode failed (line 120)".

On a computer running Windows 8 with OpenCPN 5.8.4, the Javascript version available in the plugin catalogs (master, beta or alpha) is named -1.0.0. I have installed this version and the result when loading then running PointUtility is the same. I got the message "SyntaxError: source decode failed (line 120)".

**Comment by antipole2** [comment]
The issue of which version you get for Windows 8 is a plugin issue rather than a VDR2 issue.  I have [added an issue for the plugin here](https://github.com/antipole2/JavaScript_pi/issues/91).  Please monitor that.

**Comment by Erickalon** [comment]
You are right Antipole, thank you!

**Comment by antipole2** [comment]
I suspect the issue could be with the degree symbol.  On Windows, the JavaScript engine has a real problem with it and we had to make special arrangements.

Please copy the following script into a script pane.
````
print("Degree is º\n");
print("The degree symbol from code is ", String.fromCharCode(0xB0), "\n");
````
Does it look right? Does the degree symbol in the first line look right?

Try running the script.  If it throws an error like _source code failed_, comment out the first line or remove it altogether if need be so that the second line runs.
Please let me have the output or a screenshot if it is wierd.

Repeat on Windows 8

Thanks

**Comment by Erickalon** [comment]
I am sorry, but I don't know what to do. Can you please explain me what is a script pane and how do get it? I have absolutely no experience with Java...

**Comment by antipole2** [comment]
In your console you have an upper pane for the script and a lower one for the script result.

Click on the Clear button for the upper pane to clear out the existing script.
Copy and paste my two-liner script into the top script pane and the proceed as above.

Please download the User Guide.  It does explain what you need to know about these things and takes you around the console.

**Comment by Erickalon** [comment]
OK, thanks, it's clear. So the result is the same on Windows 8 and on OpenPlotter: 
SyntaxError: source decode failed (line 0)
When running the second line alone, the result on OpenPlotter is:
The degree symbol from code is Â°
result: undefined
The result on windows 8 is:
The degree symbol from code is °
result: undefined

**Comment by antipole2** [comment]
Making progress!
Are you up for trying a special build by downloading from where I put it and importing it?

**Comment by Erickalon** [comment]
Hi Antipole, sorry for my late response.  Yes, I am ok to try a new version following your instructions.

**Comment by antipole2** [comment]
I have built a special test version that uses degree substitution on all platforms, rather than just Windows.

To install

1. Browse to the plugin's [alpha repository here](https://cloudsmith.io/~opencpn/repos/javascript-alpha/packages/)
2. Find the test builds likely at the top of the list.  Build number e51c9da.  Ignore the metadata files - it's the binaries you need
3. Download the package appropriate for your platform to somewhere on your computer. Use the green button at right-hand end of the entry.
4. You are going to  lose any scripts not saved to a file!
5. In OpenCPN open options->plugins
6. Use the Import... button to import the binary from where you stored it and click on OK
7. On the JavaScript entry in the list of plugins, click on Reinstall (it could possibly be Downgrade - that's OK) and then OK
8. The plugin will restart
9. A new script window will likely have "Test with all subs" in the default script.

Now you can retry the two-line test script. Hopefully the first line will compile OK.
Please include in your report which binary you successfully use, e.g _javascript-3.0-debian-armhfA32_

**Comment by Erickalon** [comment]
In progress! 
- On Windows 8, installed javascript-3.0-msvc-wx32-10-tarball
I have been able to load and run PointUtility that seems working fine but I just test copy and paste a waypoint.
- On OpenPlotter, installed javascript-3.0-debian-arm64-A64-12-tarball
No change unfortunately, all behaviours are unchanged.

**Comment by antipole2** [comment]
Progress...  you are up and running on Windows 8.

Regarding OpenPlotter, please do the following

1. In the JavaScript console open the plugin tools (button top right)
2. Select Diagnostics tab
3. Click on Dump.  This will open a window with dump information.
4. Copy me the first 20 lines of text
5. Below Dump is a line of sample text `‟Fancy quotes” degrees°º⁰ primes ‘’‛’′´``
6. Screenshot this
7. Click on Clean and screenshot me the window that opens

thanks

**Comment by Erickalon** [comment]
Dump file:
JavaScript plugin version 3.0
JavaScript patch 1
JavaScript tools window DPI scaling factor 1.000000
Platform	Linux 6.6.20+rpt-rpi-v8 aarch64
wxWidgets version 3.2.2.0 or 3202
OCPN API version 1.18
Duktape version 20700
Not using svg
pJavaScript_pi->m_pconfig					0x0084570c00
pJavaScript_pi->m_parent_window			0x0084c13950
pJavaScript_pi->m_floatOnTop				false
pJavaScript_pi->mRememberToggleStatus	false
favouriteFiles:
recentFiles:
	https://raw.githubusercontent.com/antipole2/PointUtility/main/pointUtility.js
	**cancel**
N2K pgn registrations: none
pJavaScript_pi->mpFirstConsole	0x0086ca7640
And the screen shots
![Capture d’écran du 2024-04-09 14-13-12](https://github.com/antipole2/PointUtility/assets/166439320/ace4d82e-a2d7-483f-8b42-e6a38c94768f)
![Capture d’écran du 2024-04-09 14-14-02](https://github.com/antipole2/PointUtility/assets/166439320/8282c42c-a63c-46c8-9c6a-8e3efde4f46a)

**Comment by antipole2** [comment]
The clean dump shows that this platform is using character codes I have not seen used before - hence the problem.  It gives me what I need, and I will let you know when I have had time to develop a fix.

**Comment by Erickalon** [comment]
Yes, you have found the issue. My Raspberry was configured with ISO-8859-1 character code, I have changed to UTF-8 and it's working fine. I don't know what is the best choice, I had kept the default one but I there is no more trouble on my other applications, I will be ok for me.
Many thanks for that!

**Comment by Erickalon** [comment]
I have de-installed JavaScript and reinstalled with the current OCPN plugin master version and that's working as with the test version, so without the clipboard position choice.

**Comment by antipole2** [comment]
With Raspberry configured correctly to  UTF-8, all is well.  So closing this.
